name: Build Google Calendar Release
run-name: ${{ github.actor }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build distribution files
        run: |
          python3 -m pip install --upgrade build
          python3 -m build
